name: BotBuild

trigger:
    branches:
     include:
        - dev
    paths:
      include:
          - bot/*
          - utils.py
          - config-dev.json
          - infra/AzureDevops/dev/Bot*


pool:
  aws-nodes

variables:
    IMAGE_REGISTRY_CONNECTION: aws uni
    IMAGE_REGISTRY: lidoror_bot_dev
    IMAGE_REPOSETORY: 700935310038.dkr.ecr.us-west-2.amazonaws.com



stages:
    - stage: BuildArtifact
      jobs:
        - job: BuildImage
          steps:

          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                GIT_COMMIT=$(git rev-parse --short HEAD)
                
                echo "GIT_COMMIT: ${GIT_COMMIT}"
                
                #
                # set env variable to allow next task to consume
                #
                echo "##vso[task.setvariable variable=GIT_COMMIT]${GIT_COMMIT}"
          
          
          - script: docker build -f bot/Dockerfile -t $(IMAGE_REGISTRY):$(GIT_COMMIT) .
            displayName: ImageBuild          

          - task: ECRPushImage@1
            displayName: PushImage
            inputs:
              awsCredentials: 'aws uni'
              regionName: 'us-west-2'
              imageSource: 'imageid'
              sourceImageId: '$(IMAGE_REGISTRY):$(GIT_COMMIT)'
              repositoryName: '$(IMAGE_REGISTRY)'
              pushTag: '$(GIT_COMMIT)'


       