trigger:
    branches:
     include:
        - dev
    paths:
      include:
          - bot/*
          - utils.py
          - config-dev.json
 
pool:
  vmImage: ubuntu-latest

variables:
    IMAGE_REGISTRY_CONNECTION: aws uni
    IMAGE_REGISTRY: lidoror_bot_dev
    IMAGE_REPOSETORY: 700935310038.dkr.ecr.eu-north-1.amazonaws.com
    TAG: $(git rev-parse --short HEAD)


stages:
    - stage: BuildArtifact
      jobs:
        - job: BuildImage
          steps:
          - task: Docker@0
            displayName: 'BuildImage'
            inputs:
              action: Build an image
              imageName: $(IMAGE_REPOSETORY)/$(IMAGE_REGISTRY):$(TAG)
              dockerFile: 'bot/Dockerfile'
          

          - task: ECRPushImage@1
            displayName: PushImage
            inputs:
              awsCredentials: 'aws uni'
              regionName: 'eu-north-1'
              imageSource: 'imageid'
              sourceImageId: '$(IMAGE_REPOSETORY)/$(IMAGE_REGISTRY):$(TAG)'
              repositoryName: '$(IMAGE_REPOSETORY)/$(IMAGE_REGISTRY):$(TAG)'
              pushTag: '$(TAG)'
          