trigger:
    branches:
     include:
        - dev
    paths:
      include:
          - bot/*
          - utils.py
          - config-dev.json
 
pool:
  vmImage: ubuntu-latest

variables:
    IMAGE_REGISTRY_CONNECTION: aws uni
    IMAGE_REGISTRY: lidoror_bot_dev
    IMAGE_REPOSETORY: 700935310038.dkr.ecr.eu-north-1.amazonaws.com



stages:
    - stage: BuildArtifact
      jobs:
        - job: BuildImage
          steps:
          - script: pwd
          - script: echo $(pwd)

          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                GIT_COMMIT=$(git rev-parse --short HEAD)
                
                echo "GIT_COMMIT: ${GIT_COMMIT}"
                
                #
                # set env variable to allow next task to consume
                #
                echo "##vso[task.setvariable variable=GIT_COMMIT]${GIT_COMMIT}"
          - task: Docker@0
            displayName: 'BuildImage'
            inputs:
              action: Build an image
              imageName: $(IMAGE_REPOSETORY)/$(IMAGE_REGISTRY):$(GIT_COMMIT)
              dockerFile: 'bot/Dockerfile'
          

          - task: ECRPushImage@1
            displayName: PushImage
            inputs:
              awsCredentials: 'aws uni'
              regionName: 'eu-north-1'
              imageSource: 'imageid'
              sourceImageId: '$(IMAGE_REPOSETORY)/$(IMAGE_REGISTRY):$(GIT_COMMIT)'
              repositoryName: '$(IMAGE_REPOSETORY)/$(IMAGE_REGISTRY):$(GIT_COMMIT)'
              pushTag: '$(GIT_COMMIT)'
          