name: botDeploy 

trigger: none

resources:
 pipelines:
  - pipeline: botdep-resource
    source: BotBuild
    trigger:
      branches:
        include:
          - dev


variables:
  APP_ENV: dev
  K8S_DEPLOYMENT_FILE: infra/k8s/bot_to_deploy.yaml
  K8S_YAML_TO_EDIT: infra/k8s/bot.yaml

stages:
    - stage: Kubectl
      jobs:
          - job: Deploy
            steps:
            
            - task: KubectlInstaller@0
              displayName: InstallKubectl
              inputs:
                kubectlVersion: '1.23.6'
        
            
            
            - task: Bash@3
              displayName: GitCommitEnv
              inputs:
                targetType: 'inline'
                script: |
                  GIT_COMMIT=$(git rev-parse --short HEAD)
                                  
                  echo "GIT_COMMIT: ${GIT_COMMIT}"
                  
                  echo "##vso[task.setvariable variable=BOT_IMAGE_NAME]700935310038.dkr.ecr.us-west-2.amazonaws.com/lidoror_bot_dev:${GIT_COMMIT}"


            - task: PythonScript@0
              displayName: PrepareYaml 
              inputs:
                scriptSource: 'filePath'
                scriptPath: 'scripts/k8s_deployment_yaml_customize.py'
          

            - task: Kubernetes@1
              inputs:
                connectionType: 'Kubernetes Service Connection'
                kubernetesServiceEndpoint: 'eks stockholm dev'
                namespace: 'lidoror-ns-dev'
                command: 'apply'
                arguments: '-f infra/k8s/bot_to_deploy.yaml'
                secretType: 'dockerRegistry'
                containerRegistryType: 'Azure Container Registry'