name: PrTesting

trigger: none

pool: 
    aws-nodes


stages:
    - stage: CheckingPylint
      jobs:
       - job: 
         steps:
          - script: |
              pip3 install pylint
              python3 -m pylint -f parseable --reports=no **/*.py 
              
            displayName: PyLintTest