name: WorkerDeployProd

trigger: none



variables:
  APP_ENV: prod
  K8S_DEPLOYMENT_FILE: infra/k8s/worker_to_deploy.yaml
  K8S_YAML_TO_EDIT: infra/k8s/worker.yaml
  WORKER_IMAGE_NAME: '700935310038.dkr.ecr.us-west-2.amazonaws.com/lidoror_worker_prod:$(TAG)'

stages:
  - stage: Kubectl
    jobs:
      - job: PrepareToDeploy
        steps:


          - task: KubectlInstaller@0
            displayName: InstallKubectl
            inputs:
              kubectlVersion: '1.23.6'


          - task: PythonScript@0
            displayName: PrepareYaml
            inputs:
              scriptSource: 'filePath'
              scriptPath: 'scripts/k8s_deployment_yaml_customize.py'



          - script: cat infra/k8s/worker_to_deploy.yaml


          - task: Kubernetes@1
            inputs:
              connectionType: 'Kubernetes Service Connection'
              kubernetesServiceEndpoint: 'eks stockholm'
              namespace: 'lidoror-ns'
              command: 'apply'
              arguments: '-f infra/k8s/worker_to_deploy.yaml'
              secretType: 'dockerRegistry'
              containerRegistryType: 'Azure Container Registry'