apiVersion: v1
kind: ServiceAccount
metadata:
  name: deploy-robot-dev
automountServiceAccountToken: false
---
apiVersion: v1
kind: Secret
metadata:
  name: deploy-robot-secret-dev
  annotations:
    kubernetes.io/service-account.name: deploy-robot-dev
type: kubernetes.io/service-account-token
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deploy-robot-role-dev
  namespace: lidoror-ns-dev
rules: # ## Customize these to meet your requirements ##
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["create", "delete", "get", "list", "watch", "update", "patch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create","update", "delete", "get", "watch", "list"]
  - apiGroups: [""]
    resources: ["services", "endpoints"]
    verbs: ["create","delete", "get", "list", "watch", "patch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "update", "delete", "get", "watch", "list"]
  - apiGroups: ["apps"]
    resources: ["statefulsets","replicasets"]
    verbs: ["watch","list","get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: global-rolebinding-lidoror-dev
  namespace: lidoror-ns-dev
subjects:
  - kind: ServiceAccount
    name: deploy-robot-dev
    namespace: lidoror-ns-dev
roleRef:
  kind: Role
  name: deploy-robot-role-dev
  apiGroup: rbac.authorization.k8s.io
